-- Reto -> DDL
Use master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE [name] = 'RetoBD')
BEGIN
	ALTER DATABASE RetoBD SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE RetoBD;
END;

CREATE DATABASE RetoBD;
GO

USE RetoBD;
GO

DROP TABLE IF EXISTS Pais;
DROP TABLE IF EXISTS Tutor;
DROP TABLE IF EXISTS Niveles;
DROP TABLE IF EXISTS Usuario;
DROP TABLE IF EXISTS Puntuacion;
DROP TABLE IF EXISTS [Admin];

-- Catálogo de Países 
CREATE TABLE Pais (
	IDPais INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL UNIQUE
);
GO

-- Catálogo de Tutores
CREATE TABLE Tutor (
	IDTutor INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL,
	ApellidoP VARCHAR(30) NOT NULL,
	ApellidoM VARCHAR(30) NOT NULL,
	Telefono VARCHAR(30) NOT NULL,
	Correo VARCHAR(50) NOT NULL UNIQUE,
);
GO

-- Catálogo de Niveles
CREATE TABLE Niveles (
	IDNivel INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL
);

-- Tabla de Usuarios
CREATE TABLE Usuario (
	IDUsuario INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPais INT NOT NULL,
	CONSTRAINT FK_Usuario_Pais FOREIGN KEY (IDPais)
	REFERENCES Pais(IDPais)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,

	IDTutor INT NOT NULL,
	CONSTRAINT FK_Usuario_Tutor FOREIGN KEY (IDTutor)
	REFERENCES Tutor(IDTutor)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,

	Nombre VARCHAR(30) NOT NULL,
	ApellidoP VARCHAR(30) NOT NULL,
	ApellidoM VARCHAR(30) NOT NULL,
	FechaNacim INT NOT NULL,
	GamerTag VARCHAR(50) NOT NULL UNIQUE,
	Contraseña VARCHAR(96) NOT NULL UNIQUE
);
GO

-- Tabla de Puntuación
CREATE TABLE Puntuacion (
	IDPuntos INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDNivel INT NOT NULL,
	CONSTRAINT FK_Puntuacion_Niveles FOREIGN KEY (IDNivel)
	REFERENCES Niveles(IDNivel)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,

	IDUsuario INT NOT NULL,
	CONSTRAINT FK_Puntuacion_Usuario FOREIGN KEY (IDUsuario)
	REFERENCES Usuario(IDUsuario)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,

	Puntos INT NOT NULL,
	Registro DATE NOT NULL
);
GO

CREATE TABLE [Admin] (
	IDAdmin INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(30) NOT NULL,
	ApellidoP VARCHAR(30) NOT NULL,
	ApellidoM VARCHAR(30) NOT NULL,
	FechaNacim INT NOT NULL,
	NombreUser VARCHAR(50) NOT NULL UNIQUE,
	Contraseña VARCHAR(96) NOT NULL UNIQUE
);
GO